#!/usr/bin/env python3
"""Convert the runmyjobs-redwood-query + runmyjobs-redwood-script skills into the flat
all-.txt "monolith" used by the RMJ-Script-Query-Agent, then verify the result.

  python3 convert.py build  [--query-skill DIR] [--script-skill DIR] [--out DIR] [--extras DIR]
  python3 convert.py verify <DATA_DIR>

build  -> OUT/SYSTEM-PROMPT.txt   (paste into the agent's system prompt field)
          OUT/data/*              (upload ALL of these to /mnt/data)
verify -> link/marker/script smoke tests on a data dir; exit code 1 on any FAIL.
"""
import argparse
import glob
import json
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TEMPLATES = os.path.join(HERE, "..", "assets", "templates")
EXTRAS = os.path.join(HERE, "..", "assets", "extras")  # bundled hand-authored guides with no upstream source
DEFAULT_QUERY = "/mnt/skills/plugins/runmyjobs-redwood-query"
DEFAULT_SCRIPT = "/mnt/skills/plugins/runmyjobs-redwood-script"
DEFAULT_OUT = "/mnt/user-data/outputs/rmj-monolith"

# upstream reference -> flat name (query refs get an sql- prefix; java refs keep their stem)
QUERY_REFS = {
    "query-cookbook.md": "sql-cookbook.txt",
    "data-model-exploration.md": "sql-data-model-exploration.txt",
    "execution-modes.md": "sql-execution-modes.txt",
    "sql-syntax-and-rules.md": "sql-syntax-and-rules.txt",
}
PROGRAMS = {  # upstream path -> flat name
    "scripts/explore.py": "explore.py.txt",
    "scripts/lookup.py": "lookup.py.txt",
    "scripts/build_model.py": "build_model.py.txt",
    "assets/model.json": "model.json.txt",
}
HAND_AUTHORED = ["00_START_HERE_JAVA.txt", "00_START_HERE_SQL.txt",
                 "RMJ-Script-Query-Agent-instruction.txt"]


def flat_ref_name(old, is_query):
    if is_query:
        return QUERY_REFS.get(old, "sql-" + old[:-3] + ".txt")
    return old[:-3] + ".txt"


def rewrite(text, refmap):
    """Rewrite skill-style paths/links into flat .txt names."""
    # markdown links to a reference (optionally with #N-anchor) -> "label (file, section N)"
    def link(m):
        label, name, sec = m.group(1), m.group(2), m.group(3)
        flat = refmap.get(name, name)
        return f"{label} ({flat}" + (f", section {sec})" if sec else ")")
    text = re.sub(
        r"\[([^\]]+)\]\((?:file:///)?(?:references/)?([a-z0-9-]+\.md)(?:#(\d+)-[^)]*)?\)",
        link, text)
    # programs: "python scripts/x.py" / "python3 scripts/x.py" / "scripts/x.py" / "assets/model.json"
    text = re.sub(r"python3? (scripts/[a-z_]+\.py)",
                  lambda m: "python3 " + PROGRAMS[m.group(1)], text)
    for old, new in PROGRAMS.items():
        text = text.replace(old, new)
    # reference files, longest first
    for old in sorted(refmap, key=len, reverse=True):
        text = re.sub(r"(?:references/)?(?<![\w-])" + re.escape(old), refmap[old], text)
    return text


def add_cookbook_markers(text):
    """Insert 'SECTION: N. Title' marker lines the START_HERE_SQL awk command relies on."""
    out, n = [], 0
    for line in text.split("\n"):
        m = re.match(r"^## (\d+)\. (.+)$", line)
        if m:
            out.append(f"=== SECTION: {m.group(1)}. {m.group(2)} ===")
            n += 1
        out.append(line)
    if n == 0:
        raise SystemExit("FAIL: no '## N. Title' headings found in cookbook; upstream format changed")
    return "\n".join(out)


def patch_program(text, name):
    """Make the program find model.json.txt next to itself (flat layout)."""
    pat = r'os\.path\.join\(HERE,\s*"\.\.",\s*"assets",\s*"model\.json"\)'
    if name in ("explore.py.txt", "lookup.py.txt"):
        if not re.search(pat, text):
            raise SystemExit(f"FAIL: DEFAULT_MODEL line not found in {name}; upstream changed")
        text = re.sub(pat, 'os.path.join(HERE, "model.json.txt")', text)
    if name == "build_model.py.txt":
        text = text.replace('default="model.json"', 'default="model.json.txt"')
    return text


def write(path, text):
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def banner(src):
    return f"SOURCE: {src} (generated by teams-agent-converter; do not hand-edit, rebuild instead)\n\n"


def extract_rules(skill_md):
    m = re.search(r"## Non-Negotiable Rules\n(.*?)\n---", skill_md, re.S)
    if not m:
        raise SystemExit("FAIL: '## Non-Negotiable Rules' section not found in query SKILL.md")
    return m.group(1).strip()


def build(a):
    out_data = os.path.join(a.out, "data")
    if os.path.isdir(a.out):
        shutil.rmtree(a.out)
    os.makedirs(out_data)
    q, s = a.query_skill, a.script_skill

    # 1. model: one shared copy; the two upstream copies must be identical
    mq, ms = (os.path.join(d, "assets", "model.json") for d in (q, s))
    if open(mq, "rb").read() != open(ms, "rb").read():
        raise SystemExit("FAIL: the two skills ship different model.json files; decide which one wins first")
    shutil.copyfile(mq, os.path.join(out_data, "model.json.txt"))
    json.load(open(os.path.join(out_data, "model.json.txt"), encoding="utf-8"))

    # 2. programs (patched model path)
    for path, flat in (("scripts/explore.py", "explore.py.txt"),
                       ("scripts/lookup.py", "lookup.py.txt"),
                       ("scripts/build_model.py", "build_model.py.txt")):
        base = q if "explore" in path else s
        text = open(os.path.join(base, path), encoding="utf-8").read()
        text = patch_program(rewrite(text, {**QUERY_REFS}), flat)
        write(os.path.join(out_data, flat), text)

    # 3. reference guides
    all_refs = {}
    for base, is_q in ((q, True), (s, False)):
        for p in sorted(glob.glob(os.path.join(base, "references", "*.md"))):
            old = os.path.basename(p)
            all_refs[old] = flat_ref_name(old, is_q)
    for base, is_q in ((q, True), (s, False)):
        for p in sorted(glob.glob(os.path.join(base, "references", "*.md"))):
            old = os.path.basename(p)
            flat = all_refs[old]
            text = rewrite(open(p, encoding="utf-8").read(), all_refs)
            if old == "query-cookbook.md":
                text = add_cookbook_markers(text)
            src = f"{os.path.basename(base)} :: {old}"
            write(os.path.join(out_data, flat), banner(src) + text)

    # 4. sql-query-rules.txt is not an upstream reference: derive it from the query SKILL.md rules
    rules = extract_rules(open(os.path.join(q, "SKILL.md"), encoding="utf-8").read())
    rules = rewrite(rules, all_refs)
    write(os.path.join(out_data, "sql-query-rules.txt"),
          banner("runmyjobs-redwood-query :: SKILL.md, section Non-Negotiable Rules")
          + "SQL QUERY STYLE / REVIEW CHECKLIST (apply to every query you write or review)\n\n" + rules + "\n")

    # 5. hand-authored layer (templates) + system prompt
    for f in HAND_AUTHORED:
        shutil.copyfile(os.path.join(TEMPLATES, f), os.path.join(out_data, f))
    shutil.copyfile(os.path.join(TEMPLATES, "SYSTEM-PROMPT.txt"), os.path.join(a.out, "SYSTEM-PROMPT.txt"))

    # 6. hand-authored extras with no upstream source (e.g. job-definition-actions.txt):
    #    bundled ones first, then --extras (which may override a bundled extra, never a generated file)
    bundled = set()
    for p in sorted(glob.glob(os.path.join(EXTRAS, "*.txt"))):
        shutil.copyfile(p, os.path.join(out_data, os.path.basename(p)))
        bundled.add(os.path.basename(p))
        print(f"bundled extra: {os.path.basename(p)}")
    if a.extras:
        for p in sorted(glob.glob(os.path.join(a.extras, "*.txt"))):
            dst = os.path.join(out_data, os.path.basename(p))
            if os.path.exists(dst) and os.path.basename(p) not in bundled:
                print(f"SKIP extra {os.path.basename(p)} (would overwrite a generated file)")
            else:
                shutil.copyfile(p, dst)
                print(f"extra copied: {os.path.basename(p)}")
    print(f"built -> {a.out}")
    return verify(out_data)


# ----------------------------------------------------------------------------- verify
def run(cmd, cwd, shell=False):
    r = subprocess.run(cmd, cwd=cwd, shell=shell, capture_output=True, text=True, timeout=120)
    return r.returncode, (r.stdout + r.stderr)


def verify(d):
    fails, warns = [], []
    ok = lambda msg: print("ok   ", msg)

    def fail(msg):
        fails.append(msg)
        print("FAIL ", msg)

    def warn(msg):
        warns.append(msg)
        print("warn ", msg)

    names = set(os.listdir(d))

    # A. every .txt filename mentioned in the hand-authored layer exists
    mentioned = {}
    for f in HAND_AUTHORED:
        if f not in names:
            fail(f"missing {f}")
            continue
        for n in set(re.findall(r"\b([A-Za-z0-9_][A-Za-z0-9_.-]*\.txt)\b", open(os.path.join(d, f)).read())):
            mentioned.setdefault(n, []).append(f)
    for n, where in sorted(mentioned.items()):
        if n not in names:
            warn(f"{n} is referenced by {', '.join(sorted(set(where)))} but is not in the folder "
                 "(hand-authored extra? pass --extras)")
    if not any(n not in names for n in mentioned):
        ok("every .txt named in the instruction/start files exists")

    # B. no leftover skill-style paths
    pat = re.compile(r"file:///|\bscripts/|\bassets/|references/[a-z0-9-]+\.md|\]\([^)]*\.md")
    leftovers = []
    for n in sorted(names):
        if n == "model.json.txt":
            continue
        for i, line in enumerate(open(os.path.join(d, n), encoding="utf-8", errors="replace"), 1):
            if pat.search(line):
                leftovers.append(f"{n}:{i}: {line.strip()[:90]}")
    if leftovers:
        for l in leftovers[:15]:
            fail("leftover skill-style path " + l)
    else:
        ok("no leftover scripts/ assets/ references/ file:/// paths")

    # C. cookbook SECTION markers work with the awk line from 00_START_HERE_SQL.txt
    cb = os.path.join(d, "sql-cookbook.txt")
    if os.path.exists(cb):
        total = len(re.findall(r"^=== SECTION: \d+\.", open(cb).read(), re.M))
        start_sql = open(os.path.join(d, "00_START_HERE_SQL.txt")).read()
        wanted = [int(x) for x in re.findall(r"sql-cookbook\.txt\s+section (\d+)", start_sql)]
        if total == 0:
            fail("sql-cookbook.txt has no '=== SECTION: N.' markers; the awk routing in 00_START_HERE_SQL.txt returns nothing")
        elif wanted and max(wanted) > total:
            fail(f"00_START_HERE_SQL.txt routes to cookbook section {max(wanted)} but only {total} exist")
        for n in range(1, total + 1):
            code, outp = run(["awk", f"/SECTION: {n}\\./{{f=1}} /SECTION: {n + 1}\\./{{f=0}} f", "sql-cookbook.txt"], d)
            first = outp.split("\n", 1)[0]
            if code or not first.startswith(f"=== SECTION: {n}.") or f"SECTION: {n + 1}." in outp:
                fail(f"awk extraction of cookbook section {n} is wrong")
        if total and not [f for f in fails if "awk extraction" in f or "SECTION" in f or "routes to" in f]:
            ok(f"awk extracts all {total} cookbook sections cleanly")
    else:
        fail("sql-cookbook.txt missing")

    # D. programs run from the flat folder and use the routing-table commands
    cmds = set()
    for f in ("00_START_HERE_SQL.txt", "00_START_HERE_JAVA.txt", "RMJ-Script-Query-Agent-instruction.txt"):
        txt = open(os.path.join(d, f)).read()
        for m in re.finditer(r"(?:python3? )?(explore|lookup)\.py\.txt ((?:inspect|path|join|find|field|session|class|refs) [A-Za-z0-9_ ]+?)(?=\s*(?:\||\)|\n|$|,|\.\s))", txt):
            args = m.group(2).strip()
            if "<" in args or ">" in args or args.split()[-1] in ("find", "field"):
                continue
            cmds.add((m.group(1), args))
    cmds |= {("explore", "find JobDefinition"), ("lookup", "session JobDefinition"),
             ("explore", 'check "select jd.* from JobDefinition jd, Partition p where jd.Partition = p.UniqueId and p.Name = \'P1112\' and jd.BranchedLLPVersion = -1"')}
    bad = 0
    for prog, args in sorted(cmds):
        code, outp = run(f"python3 {prog}.py.txt {args}", d, shell=True)
        if code != 0 or "model.json not found" in outp or not outp.strip():
            bad += 1
            fail(f"python3 {prog}.py.txt {args}  -> rc={code}: {outp.strip()[:120]}")
    if not bad:
        ok(f"{len(cmds)} explore/lookup commands from the routing tables run cleanly")

    # E. layered reachability. The agent can only go one layer down, by `bash cat <exact filename>` (or run a
    #    program), and only to a file named in the layer it is currently reading:
    #      SYSTEM-PROMPT -> instruction -> 00_START_HERE_* -> guide / program
    #    Mentions inside a guide do not count (the start files say "cat only the ONE guide you need").
    def text_of(f):
        return open(os.path.join(d, f), encoding="utf-8").read()
    sp_path = os.path.join(d, "..", "SYSTEM-PROMPT.txt")
    if os.path.exists(sp_path):
        if "RMJ-Script-Query-Agent-instruction.txt" not in open(sp_path).read():
            fail("SYSTEM-PROMPT.txt does not name the instruction file: layer 0 -> 1 is broken")
        elif not re.search(r"cat\s+RMJ-Script-Query-Agent-instruction\.txt", open(sp_path).read()):
            fail("SYSTEM-PROMPT.txt names the instruction file but not as a `cat` command")
    else:
        warn("SYSTEM-PROMPT.txt not next to the data dir; layer 0 not checked")
    instr = text_of("RMJ-Script-Query-Agent-instruction.txt") if "RMJ-Script-Query-Agent-instruction.txt" in names else ""
    for s_file in ("00_START_HERE_JAVA.txt", "00_START_HERE_SQL.txt"):
        if s_file not in instr:
            fail(f"{s_file} is not named in the instruction file: layer 1 -> 2 is broken")
    starts = "".join(text_of(f) for f in ("00_START_HERE_JAVA.txt", "00_START_HERE_SQL.txt") if f in names)
    skip = set(HAND_AUTHORED) | {"model.json.txt"}
    layered_ok = True
    for n in sorted(names):
        if n in skip:
            continue
        if n not in starts:
            layered_ok = False
            where = "only in the instruction file" if n in instr else "nowhere in the entry files"
            fail(f"{n} is named {where}, not in a START_HERE file: the agent can never reach it by cat from its router")
    # the start files must also tell the agent HOW to open things (bash cat), not search
    for f in ("00_START_HERE_JAVA.txt", "00_START_HERE_SQL.txt"):
        if f in names and not re.search(r"cd /mnt/data && cat <file>", text_of(f)):
            warn(f"{f} has no 'cd /mnt/data && cat <file>' line telling the agent how to open a guide")
    if layered_ok:
        ok("every guide/program is named in a START_HERE file (layers chain: prompt -> instruction -> start -> guide)")

    print(f"\n{len(fails)} FAIL, {len(warns)} warn")
    return 1 if fails else 0


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    b = sub.add_parser("build")
    b.add_argument("--query-skill", default=DEFAULT_QUERY)
    b.add_argument("--script-skill", default=DEFAULT_SCRIPT)
    b.add_argument("--out", default=DEFAULT_OUT)
    b.add_argument("--extras", help="dir of hand-authored .txt files with no upstream source")
    v = sub.add_parser("verify")
    v.add_argument("data_dir")
    a = ap.parse_args()
    sys.exit(build(a) if a.cmd == "build" else verify(a.data_dir))


if __name__ == "__main__":
    main()
